read commands from commands.yaml

diff --git a/vcontrold/rootfs/etc/services.d/vcontrold/run b/vcontrold/rootfs/etc/services.d/vcontrold/run
--- a/vcontrold/rootfs/etc/services.d/vcontrold/run
+++ b/vcontrold/rootfs/etc/services.d/vcontrold/run
@@ -10,6 +10,7 @@ declare config_commands
 declare config_tty
 declare config_file_vito="vito.xml"
 declare config_file_vcontrold="/etc/vcontrold/vcontrold.xml"
+declare config_file_commands="/etc/vcontrold/commands.yaml"
 
 # Fetch Vcontrold settings
 source /etc/services.d/get_vcontrold_settings.sh
@@ -17,7 +18,7 @@ source /etc/services.d/get_vcontrold_settings.sh
 # Get configuration options from user
 config_tty=$(bashio::config 'tty')
 config_deviceid=$(bashio::config 'device_id')
-config_commands=$(bashio::config 'commands')
+#config_commands=$(bashio::config 'commands')
 
 # Check if custom vito.xml file exists
 if [ -f "/config/vcontrold/vito.xml" ]; then
@@ -35,35 +36,51 @@ else
     bashio::log.info "Using default vcontrold.xml file."
 fi
 
+# Check if custom commands.yaml file exists
+if [ -f "/config/vcontrold/commands.yaml" ]; then
+    bashio::log.info "Using custom commands.yaml file."
+    config_file_commands="/config/vcontrold/commands.yaml"
+else
+    bashio::log.info "Using default commands.yaml file."
+fi
+if [ ! -f "$config_file_commands" ]; then
+    bashio::log.error "commands.yaml not found. Exit here."
+    exit 1
+fi
+
 # Cleanup old scripts
 rm -f /etc/vcontrold/1_mqtt_commands.txt /etc/vcontrold/2_mqtt.tmpl || true
 echo '#!/bin/sh' > /etc/vcontrold/2_mqtt.tmpl
 
-# Configure scripts based on commands
-commands_array=(`echo $config_commands | tr '|' ' '`)
-i=0
-for command in "${commands_array[@]}"
-do
-   :
-    ((i=i+1))
-    cmd=$(echo $command | cut -d':' -f1)
-    type=$(echo $command | cut -d':' -f2)
-    topic=$(echo $command | cut -d':' -f3)
-
+# Parse commands.yaml file and generate mqtt template file
+count=$(yq '.commands | length' "$config_file_commands")
+for ((i=0; i<count; i++)); do
+    cmd=$(yq -r ".commands[$i].command" "$config_file_commands")
+    type=$(yq -r ".commands[$i].type" "$config_file_commands")
+    topic=$(yq -r ".commands[$i].topic" "$config_file_commands")
+    if [[ $cmd == "" ]]; then
+        bashio::log.error "Command at index $i is empty. Please check your commands.yaml file."
+        exit 1
+    fi
+    if [[ $type == "" ]]; then
+        bashio::log.warning "Type for command at index $i is not set. Defaulting to STRING."
+        type="STRING"
+    fi
     if [[ $topic == "" ]]; then
+        bashio::log.warning "Type for topic at index $i is not set. Defaulting to STRING."
         topic='"$C'$i'"'
     fi
 
-    bashio::log.info "Configuring command ${i}: ${cmd} with type ${type} using topic ${topic}"
+    bashio::log.info "Configuring command ${i}: ${cmd} with type ${type} using topic '${topic}'"
     echo $cmd >> /etc/vcontrold/1_mqtt_commands.txt
 
-    R='$'$i''
+    payload='$'$i''
     if [[ $type == "STRING" ]]; then
-        R='"$R'$i'"'
+        payload='"$R'$i'"'
     fi
 
     echo 'if [ "x$E'$i'" = "xOK" ]; then' >> /etc/vcontrold/2_mqtt.tmpl
-    echo '  mosquitto_pub -h $MQTT_HOST -p $MQTT_PORT -u $MQTT_USER -P $MQTT_PASSWORD -t /devices/$MQTT_TOPIC/controls/'${topic}' -m '$R'' >> /etc/vcontrold/2_mqtt.tmpl
+    echo '  mosquitto_pub -h $MQTT_HOST -p $MQTT_PORT -u $MQTT_USER -P $MQTT_PASSWORD -t "/devices/$MQTT_TOPIC/controls/'${topic}'" -m "'${payload}'"' >> /etc/vcontrold/2_mqtt.tmpl
     echo 'fi' >> /etc/vcontrold/2_mqtt.tmpl
 done
 
